### ISSUE TITLE
Repo has no licence file. We would like to use stm32-cc3000 in one of our projects.

### ISSUE THREAD

**Issue by paul-villagesoftware** [joeferner/stm32-cc3000#1]
Hi,

I was looking to use parts of this project **(joeferner/stm32-cc3000**) in one of our solutions that pairs a cc3000 with a CortexM3.

If your intention was that the stm32-cc3000 code be usable by the wider community, please consider adding a **licence.md**.

If none of the standard licences (MIT, Apache, Unlicence, etc.) fit what you want, I'd appreciate it if we could have an email discussion to see if there is a way we could privately licence your code for use in our project.

Kind regards,
Paul

**Comment by joeferner** [comment]
Done... https://github.com/joeferner/stm32-cc3000/commit/a430bc0968bdb4a9ffa4dfc5a3d079b07b365e87

**Comment by paul-villagesoftware** [comment]
Much Appreciated.
